language: go
go:
  - "1.13.0"
install:
  - /bin/true # Disable default install script
script:
  - set -e
  - export GITHASH=$(git rev-parse HEAD) # Git commit hash is used as version string in main.go
  - go build -v -ldflags "-extldflags '-static' -X main.githash=$GITHASH"
  - diff -u <(echo -n) <(gofmt -d ./)
  - go vet .
  - go test -cover -race -v ./...
